apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: {{ .Values.application.name }}
spec:
  description: {{ .Values.application.description }} 
  displayName: {{ .Values.application.displayName }}