{{ range $component := .Values.components }}
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: {{ $component.name }}
  annotations:
    image.redhat.com/generate: "true"
    {{- if $component.pacProvision }}
    appstudio.openshift.io/pac-provision: request
    {{- end}}
spec:
  componentName: {{ $component.name }}
  application: {{ $.Values.application.name }}
  targetPort: {{ $component.targetPort }}
  source:
    git:
      url: {{ $component.git.url }}
      {{- if $component.git.context }}
      context: {{ $component.git.context }}
      {{- end }}
      {{- if $component.git.dockerfileUrl }}
      dockerfileUrl: {{ $component.git.dockerfileUrl }}
      {{- end }}
      {{- if $component.git.devfileUrl }}
      devfileUrl: {{ $component.git.devfileUrl }}
      {{- end }}
{{ end }}